language: julia
julia:
    - 0.3
    - 0.4
    - 0.5
    - nightly
notifications:
    email: false
script:
    - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir())/SDE`); Pkg.resolve()'
    - julia -e 'using SDE; @assert isdefined(:SDE); @assert typeof(SDE) === Module'
    - julia test/runtests.jl travis
